version: '3'
services:
    perseal:
        build: ./perseal
        container_name: perseal
        env_file: .env
        command: /go/bin/perseal
        ports:
            - "8082:8082"
    #perseal-ui:
     #   build: ./perseal-ui
     #   ports:
      #      - "4200:80"
       # volumes:
        #    - "/app/node_modules"
         #   - ".:/app"
