version: '3'
services:
    perseal:
        build: 
            context: ./perseal
            args:
                PERSEAL_SIGN_P12: ${PERSEAL_SIGN_P12}
                SIGN_KEY_PASS: ${SIGN_KEY_PASS}
        container_name: perseal
        env_file: .env
        command: /go/bin/perseal
        ports:
            - "$PERSEAL_EXT_PORT:$PERSEAL_INT_PORT"
