version: '3'
services:
    perseal:
        build: ./perseal
        container_name: perseal
        env_file: .env
        command: /go/bin/perseal
        ports:
            - "$PERSEAL_EXT_PORT:$PERSEAL_INT_PORT"
